name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Flutter Manually
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b stable /opt/flutter
          echo "/opt/flutter/bin" >> $GITHUB_PATH

      - name: Build APK Release
        run: |
          flutter config --no-analytics
          flutter create . --org com.hondasales.app --project-name honda_sales_app
          flutter pub get
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Honda-Sales-App
          path: build/app/outputs/flutter-apk/app-release.apk
